SESSION_ID:
BATTERY_LEVEL: 5 # value in %
CHARGING_PORT: 'CHADEMO' # DC: CHAdeMO >= 50kW | AC >= 6.6kW (europe)
MAX_BATTERY_CAPACITY_IN_KWH: 64 # max battery capacity in KWH
ACTUAL_BATTERY_STATUS_IN_KWH: 0 # actual bettery capacity in KWH
BATTERY_VOLTAGE: 356
COOLING_SYSTEM: "PASSIVE" # LIQUID = HIGH EFECTIVE | AIR = MEDIUM EFECTIVE | PASSIVE = LOW EFFECTIVE
LOG_LEVEL_VEHICLE: "debug"
EFFECTIVE_CHARGING_CAP: 90 # value in % where charging uses full power. After this cap, 'ACTUAL_KW_PER_MIN' will be divided by 'VOLTAGE_DROP'

